### ISSUE TITLE
hangman

### ISSUE THREAD

**Issue by prajjyadav** [prajjyadav/Python-Scripts#14]
write a code for hangman game in python

**Comment by shloka-gupta** [comment]
i would like to do this

**Comment by RaviKarrii** [comment]
Can I Try this?

**Comment by dishak331** [comment]
I would like to try this

**Comment by dishak331** [comment]
please review my pr #16

**Comment by xPolar** [comment]
Hey there, I'd like to take a shot at this!

**Comment by Aman-Jamshed** [comment]
Hey @prajjyadav Kindly review my PR #20. Please merge my PR as this my first Hacktoberfest
